# Generated by Django 3.1.5 on 2021-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classnum',
            field=models.PositiveIntegerField(verbose_name='Classnum'),
        ),
    ]
