# Generated by Django 3.1.5 on 2021-02-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210201_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classnum',
            field=models.PositiveIntegerField(verbose_name='Classnum'),
        ),
    ]
